# Generated by Django 4.1.4 on 2023-02-08 15:54

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('maintenance', '0020_contract_turf_apps_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_type', models.CharField(choices=[('MO', 'Mowing'), ('PR', 'Pruning'), ('SC', 'Spring Cleanup'), ('FC', 'Fall Cleanup'), ('LF', 'Leaf Removal'), ('IS', 'Inspection'), ('IR', 'Irrigation'), ('OT', 'Other, Please make notes.')], default='MO', max_length=2)),
                ('visit_date', models.DateField(default=datetime.date.today)),
                ('crewsize', models.CharField(max_length=128)),
                ('total_man_hours', models.IntegerField()),
                ('notes', models.CharField(blank=True, max_length=1024, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('contract', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='maintenance.contract')),
            ],
        ),
    ]
