# Generated by Django 4.1.4 on 2023-02-09 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0002_visittype_alter_visit_visit_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visit',
            old_name='visit_type',
            new_name='visit_type_name',
        ),
        migrations.RemoveField(
            model_name='visittype',
            name='visit_type',
        ),
        migrations.AddField(
            model_name='visittype',
            name='visit_type_name',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='visit',
            name='total_man_hours',
            field=models.FloatField(),
        ),
    ]
