# Generated by Django 4.1.4 on 2023-02-09 16:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0003_rename_visit_type_visit_visit_type_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visit',
            name='date_created',
        ),
        migrations.AlterField(
            model_name='visit',
            name='visit_date',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='visittype',
            name='visit_type_name',
            field=models.CharField(max_length=120),
        ),
    ]
