# Generated by Django 4.1.4 on 2023-02-10 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_alter_employee_license'),
        ('visits', '0004_remove_visit_date_created_alter_visit_visit_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visit',
            old_name='crewsize',
            new_name='crew_size',
        ),
        migrations.AddField(
            model_name='visit',
            name='crew_leader',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee.employee'),
        ),
    ]
