# Generated by Django 4.1.4 on 2023-12-15 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0005_rename_crewsize_visit_crew_size_visit_crew_leader'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visit',
            old_name='contract',
            new_name='visit_contract',
        ),
    ]
