# Generated by Django 4.1.4 on 2024-02-08 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0023_contract_irrigation_inspections'),
        ('visits', '0006_rename_contract_visit_visit_contract'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='visit_customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='maintenance.customer'),
        ),
    ]
