# Generated by Django 4.1.4 on 2024-02-08 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0007_visit_visit_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visit',
            name='visit_customer',
        ),
    ]
