# Generated by Django 4.1.4 on 2023-02-10 12:40

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=120)),
                ('last_name', models.CharField(max_length=120)),
                ('work_phone', phone_field.models.PhoneField(blank=True, max_length=31, null=True)),
                ('personal_phone', phone_field.models.PhoneField(blank=True, max_length=31, null=True)),
                ('license_state', models.CharField(default='MD', max_length=2)),
                ('license', models.CharField(max_length=120)),
            ],
        ),
    ]
