# Generated by Django 4.2.30 on 2026-05-26 22:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employee', '0005_employee_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='is_office_staff',
            field=models.BooleanField(default=False, help_text='Can be assigned as an estimator on landscape bids'),
        ),
        migrations.AddField(
            model_name='employee',
            name='user',
            field=models.OneToOneField(blank=True, help_text="Link to this employee's login account", null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
