# Generated by Django 4.2.30 on 2026-05-28 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0006_employee_is_office_staff_employee_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='license',
            field=models.CharField(blank=True, max_length=120, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='license_state',
            field=models.CharField(blank=True, default='MD', max_length=2),
        ),
    ]
