# Generated by Django 4.2.30 on 2026-05-26 18:59

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0005_employee_uuid'),
        ('maintenance', '0027_customer_is_general_contractor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=255)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('amount', models.FloatField(blank=True, null=True)),
                ('phase', models.CharField(choices=[('estimating', 'Estimating'), ('submitted', 'Submitted'), ('on_hold', 'On Hold'), ('likely', 'Likely'), ('awarded', 'Awarded'), ('lost', 'Lost'), ('dead', 'Dead')], default='estimating', max_length=20)),
                ('status', models.CharField(blank=True, choices=[('in_progress', 'In Progress'), ('scheduled', 'Scheduled'), ('paused', 'Paused'), ('delayed', 'Delayed'), ('completed', 'Completed'), ('waiting', 'Waiting')], max_length=20, null=True)),
                ('bid_submitted', models.DateField(blank=True, null=True)),
                ('last_contact', models.DateField(blank=True, null=True)),
                ('next_follow_up', models.DateField(blank=True, null=True)),
                ('follow_up_notes', models.TextField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('contract_signed', models.BooleanField(default=False)),
                ('warranty_days', models.IntegerField(blank=True, help_text='Warranty period in days', null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='maintenance.customer')),
                ('estimator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee.employee')),
            ],
            options={
                'ordering': ['next_follow_up', 'project_name'],
            },
        ),
        migrations.CreateModel(
            name='DailyLogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('entry', models.TextField()),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee.employee')),
                ('bid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landscape.bid')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChangeOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('amount', models.FloatField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('date_submitted', models.DateField(blank=True, null=True)),
                ('scope_of_work', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landscape.bid')),
            ],
        ),
    ]
