# Generated by Django 4.2.30 on 2026-05-27 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landscape', '0002_create_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bid',
            name='state',
            field=models.CharField(blank=True, default='MD', max_length=2),
        ),
        migrations.AddField(
            model_name='bid',
            name='zip',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
