# Generated by Django 4.2.30 on 2026-05-27 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landscape', '0003_bid_city_state_zip'),
    ]

    operations = [
        migrations.AddField(
            model_name='changeorder',
            name='co_number',
            field=models.CharField(blank=True, help_text='Assigned only when status is Approved', max_length=50, null=True, verbose_name='CO Number'),
        ),
    ]
