# Generated by Django 4.2.30 on 2026-05-27 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landscape', '0004_co_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='warranty_days',
            field=models.IntegerField(blank=True, default=365, help_text='Warranty period in days'),
        ),
    ]
