# Generated by Django 4.2.30 on 2026-05-28 17:14

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0007_alter_employee_license_alter_employee_license_state'),
        ('landscape', '0005_warranty_days_default'),
    ]

    operations = [
        migrations.CreateModel(
            name='BidDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='bid_documents/')),
                ('name', models.CharField(max_length=255)),
                ('doc_type', models.CharField(choices=[('proposal', 'Proposal'), ('signed_contract', 'Signed Contract'), ('estimating_sheet', 'Estimating Sheet'), ('other', 'Other')], max_length=20)),
                ('other_desc', models.CharField(blank=True, max_length=100)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('bid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landscape.bid')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee.employee')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
