# Generated by Django 4.2.30 on 2026-05-28 17:37

from django.db import migrations, models
import landscape.models


class Migration(migrations.Migration):

    dependencies = [
        ('landscape', '0006_biddocument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biddocument',
            name='file',
            field=models.FileField(upload_to=landscape.models._bid_doc_upload_path),
        ),
    ]
