# Generated by Django 4.2.30 on 2026-05-28 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landscape', '0007_alter_biddocument_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='biddocument',
            name='name',
        ),
        migrations.AddField(
            model_name='biddocument',
            name='note',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='biddocument',
            name='doc_type',
            field=models.CharField(choices=[('proposal', 'Proposal'), ('signed_contract', 'Signed Contract'), ('estimating_sheet', 'Estimating Sheet'), ('plans', 'Plans'), ('change_order', 'Change Order'), ('as_built', 'As Built'), ('other', 'Other')], max_length=20),
        ),
    ]
