# Generated by Django 4.1.1 on 2022-09-12 00:14

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('add1', models.CharField(max_length=100, null=True)),
                ('add2', models.CharField(max_length=100, null=True)),
                ('city', models.CharField(max_length=100, null=True)),
                ('state', models.CharField(max_length=100, null=True)),
                ('zip', models.CharField(max_length=2, null=True)),
                ('contact_name', models.CharField(max_length=100, null=True)),
                ('phone1', phone_field.models.PhoneField(blank=True, max_length=31)),
                ('phone2', phone_field.models.PhoneField(blank=True, max_length=31)),
                ('email', models.EmailField(max_length=254, null=True)),
            ],
        ),
    ]
