# Generated by Django 4.1.1 on 2022-09-12 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0003_alter_customer_state_alter_customer_zip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='add2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
