# Generated by Django 4.1.1 on 2022-09-12 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0005_contract'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contract',
            old_name='state_date',
            new_name='start_date',
        ),
    ]
