# Generated by Django 4.1.1 on 2022-09-12 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0006_rename_state_date_contract_start_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='start_date',
        ),
    ]
