# Generated by Django 4.1.1 on 2022-09-12 16:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0007_remove_contract_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='start_date',
            field=models.DateField(default=datetime.date(2022, 9, 12)),
        ),
    ]
