# Generated by Django 4.1.1 on 2022-09-13 03:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0009_alter_contract_start_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Soldby',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salesman', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='contract',
            name='visits',
            field=models.IntegerField(default=24),
        ),
        migrations.AddField(
            model_name='contract',
            name='salesman',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='maintenance.soldby'),
        ),
    ]
