# Generated by Django 4.1.1 on 2022-09-14 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0010_soldby_alter_contract_visits_contract_salesman'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='notes',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='notes',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='add1',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='add2',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='city',
            field=models.CharField(default='Baltimore', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(default='MD', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='zip',
            field=models.CharField(default='21220', max_length=5, null=True),
        ),
    ]
