# Generated by Django 4.1.1 on 2022-09-14 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0011_contract_notes_customer_notes_alter_customer_add1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='billing_add1',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='billing_add2',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='billing_city',
            field=models.CharField(default='Baltimore', max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='billing_name',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='billing_ref',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='billing_state',
            field=models.CharField(default='MD', max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='billing_zip',
            field=models.CharField(default='21220', max_length=5, null=True),
        ),
    ]
