# Generated by Django 4.1.4 on 2023-01-27 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0013_alter_customer_billing_add1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mulchcolor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='contract',
            old_name='salesman',
            new_name='salesrep',
        ),
        migrations.RenameField(
            model_name='contract',
            old_name='name',
            new_name='site_name',
        ),
        migrations.AddField(
            model_name='contract',
            name='aeration_overseed',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='contract_description',
            field=models.CharField(default='Maintenance Contract', max_length=200),
        ),
        migrations.AddField(
            model_name='contract',
            name='flowers_fall',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='flowers_spring',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='hours_total_contract',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='irrigation',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='leaf_cleanup',
            field=models.SmallIntegerField(default=1, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='mulch_fall',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='mulch_yd',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='payments',
            field=models.IntegerField(default=12, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='sq_mulch',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='sq_turf',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='turf_apps',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='visits',
            field=models.IntegerField(default=24, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='city',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='zip',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='mulch_color',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='maintenance.mulchcolor'),
        ),
    ]
