# Generated by Django 4.1.4 on 2023-01-27 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0015_alter_contract_irrigation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='aeration_overseed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='contract',
            name='turf_apps',
            field=models.BooleanField(default=False),
        ),
    ]
