# Generated by Django 4.1.4 on 2023-02-03 14:37

from django.db import migrations, models
import maintenance.models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0017_alter_contract_mulch_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='end_date',
            field=models.DateField(default=maintenance.models.get_end_date),
        ),
    ]
