# Generated by Django 4.1.4 on 2023-02-06 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0019_alter_contract_mulch_fall'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='turf_apps_count',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
