# Generated by Django 4.1.4 on 2023-02-09 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0020_contract_turf_apps_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='mulch_yd',
            field=models.FloatField(default=0, null=True),
        ),
    ]
