# Generated by Django 4.1.4 on 2023-02-09 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0021_alter_contract_mulch_yd'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='tree_rings',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
