# Generated by Django 4.1.4 on 2026-05-15 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0024_rename_customer_contract_site_customer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
