# Generated by Django 4.2.30 on 2026-05-26 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0026_contract_uuid_customer_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='is_general_contractor',
            field=models.BooleanField(default=False),
        ),
    ]
